# Generated by Django 4.2.24 on 2025-10-15 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('voice', '语音评估'), ('face', '面部评估'), ('gait', '步态评估')], max_length=20)),
                ('features', models.JSONField(verbose_name='特征数据')),
                ('prediction', models.JSONField(verbose_name='预测结果')),
                ('severity_bucket', models.IntegerField(verbose_name='严重程度分级')),
                ('total_updrs', models.FloatField(blank=True, null=True, verbose_name='UPDRS总分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评估结果',
                'verbose_name_plural': '评估结果',
                'db_table': 'assessment_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
